### PR TITLE
Add Support for Off Grid and Refresh Tokens

### PR DESCRIPTION
**Pull request by x10send**
Added support for islanding when connected to the gateway locally (Hubitat Only).
Added support for specifying Refresh Token in addition to Access Token removing the need for external api.

### CODE REVIEW

**Comment by DarwinsDen** [comment]
Thank you! I had made local updates to add a refresh token a while back but never tested enough to release. I'll go with your updates here - I know the users have been clamoring for it. And I'm intrigued with the islanding updates for Hubitat. I hope to get this merged in the next day or so. Very much appreciated.

**Comment by x10send** [comment]
Happy to help, I added the On/Off-Grid capability a couple of months ago
and have been running it without issue.  The refresh token logic is based
off of a python implementation I found online that I had originally set up
as an API endpoint on my local network.  The python based version of that
logic was in use for a couple of months before I ported it to the smartapp
over the weekend.  LMK if you need me to make any changes.

**Comment by DarwinsDen** [comment]
I've updated the baseline with your changes + a few small tweaks. I didn't do a direct merge since I went through the SmartThings GitHub integration. I did change the token refresh scheduling to be based on the expiration time (up to a max of 30 days) out of probably unnecessary concern over raising issues with the Tesla server. I didn't explore the differences, but refreshed tokens using your refresh code were sticking around for 45 days, while tokens using my original refresh logic were expiring every 8 hours. Needless to say, I stayed with your logic. I'll give it a little time for burn-in testing before publicizing the update. Thank you again!

Curious - how are you using the Off/On Grid commanding/scheduling?

**Comment by x10send** [comment]
> Curious - how are you using the Off/On Grid commanding/scheduling?

I could only get it to work with the local gateway unfortunately.  I use it in 2 scenarios, to go off grid during on peak hours (so scheduled), and to go on/off grid based on the state of charge (on grid if <10% / off grid > 90%).

**Comment by DarwinsDen** [comment]
Interesting. I haven't really messed with the off grid feature, but I did schedule a grid on/off event with your changes and all appeared to work well. Are there any key advantages to going off grid during peak hours as opposed to setting reserve to 0% in self-consumption mode?

**Comment by x10send** [comment]
The plan that I'm on has demand charges.  I noticed a  few times the TEG pulling small amounts from the grid even when on peak.  When I trigger off grid that went away.  That being said, I still don't have the update that allows for multiple on peak periods so it may be fixed by that update.

I went through your updates, they look great.  I'll close this PR.

**Comment by DarwinsDen** [comment]
Excellent thanks. That makes sense from a demand management perspective. Really appreciate these updates and I'm sure the other users will as well.

**Pull request closed without merging**
